export default {
  CONTENT_UPDATE_LOCAL: 'CONTENT_UPDATE_LOCAL',
  TITLE_UPDATE_LOCAL: 'TITLE_UPDATE_LOCAL',
  ADD_BLOG: 'ADD_BLOG',
  ADD_BLOG_LIST: 'ADD_BLOG_LIST',
  ADD_CURRENT_BLOG: 'ADD_CURRENT_BLOG'
};